language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t tuckergbarton/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true tuckergbarton/docker-react npm run test